"""empty message

Revision ID: 6b74b7c3c3d7
Revises: 64adf34a98db
Create Date: 2023-07-05 17:01:17.939565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b74b7c3c3d7'
down_revision = '64adf34a98db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_triggerable_process_model', schema=None) as batch_op:
        batch_op.alter_column('process_model_identifier',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_triggerable_process_model', schema=None) as batch_op:
        batch_op.alter_column('process_model_identifier',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
